#!/bin/sh
echo "IM AM LAXLINUX-CL" >> /tmp/xinitrc.log
synclient EmulateTwoFingerMinW=7 &
synclient EmulateTwoFingerMinZ=20 &
# synclient VertTwoFingerScroll=1 &
synclient HorizTwoFingerScroll=1 &
# syndaemon -i 2 & # Prevent mouse from clicking while typing (for 2sec)
xbacklight -display :0 -set 100 &
xautolock -locker "i3lock -b -i /home/pschmitt/pictures/wallpapers/me\ gusta\ mucho_1366.png" -time 3 &
